name: 2024_07_25_thp1
channels:
 - conda-forge
 - bioconda
 - defaults
dependencies:

   # R packages
  - r-irkernel  
  - r-base
  - r-shinyhelper
  - r-shiny
  - r-shinyjs
  - r-dplyr
  - r-ggpmisc
  - r-ggplot2
  - r-plotly
  - r-dt
  - r-openxlsx


  # Bioconductor
  - bioconductor-edger
  - bioconductor-biomar
  
  # JupyterLab for running notebooks
  - jupyterlab
  
  # Radian for improved R REPL (optional)
  - radian